[package]
name = "problem_11"
version = "0.1.0"
authors = ["t3xhno <t3xhnolainx@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
